
#List of curio slot type settings
[[curiosSettings]]
	identifier = "back"
	hasCosmetic = true

[[curiosSettings]]
	identifier = "belt"
	hasCosmetic = true

[[curiosSettings]]
	identifier = "body"
	hasCosmetic = true

[[curiosSettings]]
	identifier = "charm"
	hasCosmetic = true

[[curiosSettings]]
	identifier = "head"
	hasCosmetic = true

[[curiosSettings]]
	identifier = "hands"
	hasCosmetic = true

[[curiosSettings]]
	identifier = "necklace"
	hasCosmetic = true

[[curiosSettings]]
	identifier = "ring"
	hasCosmetic = true

[[curiosSettings]]
	identifier = "feet"
	hasCosmetic = true

