
#General settings
[general]
	#How often Sylphs spawn
	#Range: 0 ~ 100
	sylphWeight = 5
	#Should the Wilden Hunter attack animals?
	hunterHuntsAnimals = true
	#How often Wilden Stalkers spawn
	#Range: 0 ~ 200
	wstalkerWeight = 50
	#Dimensions where hostile mobs will not spawn. Ex: ["minecraft:overworld", "undergarden:undergarden"]. . Run /forge dimensions for a list.
	dimensionBlacklist = ["aoa3:abyss", "aoa3:barathos", "aoa3:candyland", "aoa3:celeve", "aoa3:creeponia", "aoa3:crystevia", "aoa3:deeplands", "aoa3:dustopia", "aoa3:gardencia", "aoa3:greckon", "aoa3:haven", "aoa3:iromine", "aoa3:lborean", "aoa3:lelyetia", "aoa3:lunalus", "aoa3:mysterium", "aoa3:precasia", "aoa3:runandor", "aoa3:shyrelands", "aoa3:structure", "aoa3:vox_ponds", "twilightforest:twilightforest"]
	#Should the Wilden Stalker attack animals?
	stalkerHuntsAnimals = false
	#Should the Wilden Defender attack animals?
	defenderHuntsAnimals = false
	#How often Wilden Hunter spawn
	#Range: 0 ~ 200
	whunterWeight = 50
	#Spawn Arcane Ore in the world
	genOre = true
	#Spawn a book in the players inventory on login
	spawnBook = false
	#Spawn Mana Berry Bushes in the world
	genBerries = true
	#How often Wilden Guardians spawn
	#Range: 0 ~ 200
	wguardianWeight = 50
	#Rate of tree spawn per chunk
	#Range: 0.0 ~ 1.0
	genTrees = 0.002
	#How often Carbuncles spawn
	#Range: 0 ~ 100
	carbuncleWeight = 5
	#Archwood forest spawn weight
	#Range: > 0
	archwoodForest = 3
	#Crystallizer output item. Do not use a wrong ID!
	crystallizer_output = "ars_nouveau:mana_gem"
	#How often Drygmys spawn
	#Range: 0 ~ 100
	drygmyWeight = 3

#Mana
[mana]
	#Base mana regen in seconds
	#Range: > 0
	baseRegen = 5
	#Max mana bonus for tier of book
	#Range: > 0
	tierMax = 50
	#How often max and regen will be calculated, in ticks. NOTE: Having the base mana regen AT LEAST this value is recommended.
	#Range: 1 ~ 20
	updateInterval = 5
	#Mana Boost value per level
	#Range: > 0
	manaBoost = 25
	#Regen bonus per potion level
	#Range: > 0
	potionRegen = 10
	#Max mana bonus per glyph
	#Range: > 0
	glyphmax = 15
	#(enchantment) Mana regen per second per level
	#Range: > 0
	manaRegenEnchantment = 2
	#Base max mana
	#Range: > 0
	baseMax = 100
	#Regen bonus per glyph
	#Range: 0.0 ~ 2.147483647E9
	glyphRegen = 0.33

